# Generated by Django 5.0.3 on 2024-03-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listcars',
            table='listcars',
        ),
    ]
